# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['time']},
        ),
        migrations.RenameField(
            model_name='emailmessage',
            old_name='recipient',
            new_name='recipient_str',
        ),
    ]
