# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 17:59
from __future__ import unicode_literals

from django.db import migrations


def assign_recipients(apps, schema_editor):
    EmailMessage = apps.get_model('j60adm', 'EmailMessage')
    EmailAddress = apps.get_model('j60adm', 'EmailAddress')
    addresses = {e.address: e for e in EmailAddress.objects.all()}
    for e in EmailMessage.objects.all():
        e.recipient = addresses[e.recipient_str]
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0003_emailmessage_recipient'),
    ]

    operations = [
        migrations.RunPython(assign_recipients),
    ]
