# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0004_assign_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='person',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='recipient_str',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='j60adm.EmailAddress'),
        ),
    ]
