# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0005_remove_recipient_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['time']},
        ),
    ]
