# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0006_registration_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='letter_bounced',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
