# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0007_person_letter_bounced'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='emailmessage',
            options={'ordering': ['recipient']},
        ),
    ]
