# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j60adm', '0008_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
